name: Deploy
on:
  pull_request: 
    types: [opened, edited, closed, synchronize]
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build Next.js Demo
        run: npm run build
        working-directory: examples
      - name: Build and deploy to gh-pages
        uses: sauloxd/review-apps@1.3.3
        with:
          build-cmd: ''
          dist: 'examples/out'
