name: Deploy
on:
  pull_request: 
    types: [opened, edited, closed, synchronize]
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install Root Dependencies
        run: npm ci
      - name: Build and deploy to gh-pages
        uses: sauloxd/review-apps@v1.3.3
        with:
          build-cmd: npm run build-storybook
          dist: 'storybook-static'
