name: Lint
on:
  push: 
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: Install Dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint